import 'dart:math';
import 'package:flutter/material.dart';
import 'package:lista_mercado/models/categoria.dart';

class Categorias {
  static const Categoria carnes = Categoria.carnes;
  static const Categoria hortifruti = Categoria.hortifruti;
  static const Categoria padaria = Categoria.padaria;
  static const Categoria laticinios = Categoria.laticinios;
  static const Categoria frios = Categoria.frios;
  static const Categoria limpeza = Categoria.limpeza;
  static const Categoria higienePessoal = Categoria.higienePessoal;
  static const Categoria bebidas = Categoria.bebidas;
  static const Categoria mercearia = Categoria.mercearia;
  static const Categoria indefinido = Categoria.indefinido;

  static Categoria obterCategoriaAleatoria() {
    final List<Categoria> todasCategorias = [
      carnes,
      hortifruti,
      padaria,
      laticinios,
      frios,
      limpeza,
      higienePessoal,
      bebidas,
      mercearia,
      indefinido,
    ];

    final Random random = Random();
    final int indiceAleatorio = random.nextInt(todasCategorias.length);

    return todasCategorias[indiceAleatorio];
  }

  static Color obterCorPorDescricao(String descricao) {
    final Map<String, Categoria> mapaCategorias = {
      'Carnes': carnes,
      'Hortifruti': hortifruti,
      'Padaria': padaria,
      'Laticínios': laticinios,
      'Frios': frios,
      'Limpeza': limpeza,
      'Higiene Pessoal': higienePessoal,
      'Bebidas': bebidas,
      'Mercearia': mercearia,
      'Indefinido': indefinido,
    };

    return mapaCategorias[descricao]?.cor ?? Colors.grey[50]!;
  }

  static Color obterCorSecundariaPorDescricao(String descricao) {
    final Map<String, Categoria> mapaCategorias = {
      'Carnes': carnes,
      'Hortifruti': hortifruti,
      'Padaria': padaria,
      'Laticínios': laticinios,
      'Frios': frios,
      'Limpeza': limpeza,
      'Higiene Pessoal': higienePessoal,
      'Bebidas': bebidas,
      'Mercearia': mercearia,
      'Indefinido': indefinido,
    };

    return mapaCategorias[descricao]?.corSecundaria ?? Colors.grey[200]!;
  }

  static List<Categoria> obterTodasCategorias() {
    return [
      carnes,
      hortifruti,
      padaria,
      laticinios,
      frios,
      limpeza,
      higienePessoal,
      bebidas,
      mercearia,
      indefinido,
    ];
  }

  static String abreviarCategoria(String nomeCategoria) {
    return nomeCategoria.substring(0, 5).toUpperCase();
  }

  static String defineCategoriaAuto(String nomeProduto) {
    //print(nomeProduto);
    //print('********************************************************');
    nomeProduto = nomeProduto.trim();
    //print(nomeProduto);

    List<String> carnes = [
      'alcatra',
      'anchova',
      'asinha',
      'atum',
      'bacon',
      'bacalhau',
      'bacalhau fresco',
      'barriga de porco',
      'bisteca',
      'bisteca suína',
      'bochecha de boi',
      'boi ralado',
      'braço de cordeiro',
      'buchada',
      'cabrito',
      'capitao',
      'carne',
      'carne de pato',
      'carne de sol',
      'carne moida',
      'carne moída',
      'carne seca',
      'carneiro',
      'cavala',
      'chouriço',
      'coelho',
      'cordeiro',
      'costela',
      'costela de boi',
      'costela de cordeiro',
      'costela minga',
      'costela suína',
      'costelinha suína',
      'coxao duro',
      'coxão duro',
      'coxao mole',
      'coxão mole',
      'coxa de frango',
      'cupim',
      'cupim bovino',
      'cupim de búfalo',
      'dobradinha',
      'escabeche',
      'fígado bovino',
      'fígado de frango',
      'fígado de pato',
      'fígado suíno',
      'file de peixe',
      'filé de peixe',
      'fraldinha',
      'frango',
      'hamburguer',
      'hambúrguer',
      'javali',
      'joelho de porco',
      'joelho suíno',
      'lagarto',
      'língua',
      'lingua',
      'linguiça',
      'linguiça calabresa',
      'linguiça de frango',
      'linguiça toscana',
      'lombo bovino',
      'lombo suíno',
      'maminha',
      'matambre',
      'meio da asa',
      'miolo de alcatra',
      'miudos',
      'miúdos',
      'moela',
      'mocoto',
      'mocotó',
      'morcela',
      'mortadela',
      'ossobuco',
      'pá suína',
      'paleta',
      'panceta',
      'patinho',
      'pato',
      'peito de frango',
      'peito de peru',
      'peixe',
      'pernil',
      'peru',
      'picanha',
      'picanha suína',
      'pintado',
      'polvo',
      'ponta de peito',
      'presunto',
      'quibe cru',
      'rabada',
      'salmão',
      'salame',
      'salsicha',
      'salsichão',
      'sardinha',
      'sobrecoxa',
      'sobrepaleta',
      'solha',
      'tainha',
      'tambaqui',
      'tartaruga',
      'tripa',
      'tripas',
      'truta',
      'vazio',
      'vitela'
    ];

    List<String> hortifruti = [
      'abacate',
      'abacaxi',
      'abóbora',
      'abobora',
      'abobrinha',
      'acerola',
      'aipo',
      'alface',
      'alho',
      'ameixa',
      'amora',
      'aspargos',
      'atemoia',
      'banana',
      'batata',
      'batata-baroa',
      'batata-doce',
      'batata inglesa',
      'berinjela',
      'beterraba',
      'brocolis',
      'brócolis',
      'caqui',
      'carambola',
      'cebola',
      'cenoura',
      'cereja',
      'coco',
      'couve',
      'couve-flor',
      'damasco',
      'endívia',
      'endivia',
      'espinafre',
      'figo',
      'framboesa',
      'gengibre',
      'goiaba',
      'inhame',
      'jaca',
      'jiló',
      'jilo',
      'kiwi',
      'laranja',
      'lima',
      'limão',
      'limao',
      'lichia',
      'maçã',
      'maca',
      'mamão',
      'mamao',
      'mandioquinha',
      'manga',
      'maracujá',
      'maracuja',
      'melancia',
      'melão',
      'melao',
      'mexerica',
      'morango',
      'nectarina',
      'nêspera',
      'nespera',
      'pepino',
      'pêssego',
      'pessego',
      'pimentão',
      'pimentao',
      'pinha',
      'pitanga',
      'quiabo',
      'radicchio',
      'rabanete',
      'repolho',
      'romã',
      'roma',
      'rúcula',
      'rucula',
      'salsa',
      'salsão',
      'salsao',
      'tamarindo',
      'tomate',
      'tomate cereja',
      'uva',
      'vagem',
      'vergamota',
      'zuchini',
      'acelga',
      'agrião',
      'agriao',
      'alcachofra',
      'almeirão',
      'almeirao',
      'ameixa seca',
      'anona',
      'araticum',
      'babaco',
      'bardana',
      'beldroega',
      'caju',
      'cambuci',
      'camu-camu',
      'camu camu',
      'canistel',
      'cardo',
      'caroço de abacate',
      'castanha de caju',
      'castanha portuguesa',
      'catalonha',
      'chuchu',
      'coentro',
      'couve de bruxelas',
      'dióspiro',
      'diospiro',
      'erva doce',
      'ervilha',
      'fava',
      'feijão de corda',
      'feijao de corda',
      'feijão verde',
      'feijao verde',
      'funcho',
      'gilo',
      'guariroba',
      'ingá',
      'inga',
      'jambo',
      'jambu',
      'jenipapo',
      'lentilha',
      'maçã verde',
      'maca verde',
      'murici',
      'nirá',
      'nira',
      'palmito',
      'pequi',
      'pitaya',
      'ponkan',
      'pupunha',
      'seriguela',
      'tangerina',
      'topinambur',
      'urtiga',
      'uvaia'
    ];

    List<String> padaria = [
      'pao',
      'pão',
      'baguete',
      'croissant',
      'pao de forma',
      'pão de forma',
      'pao de queijo',
      'pão de queijo',
      'bisnaguinha',
      'pao integral',
      'pão integral',
      'rosca',
      'pao sirio',
      'pão sírio',
      'pao de centeio',
      'pão de centeio',
      'broa',
      'focaccia',
      'ciabatta',
      'torta',
      'bolo',
      'brownie',
      'bolacha',
      'sonho',
      'pao doce',
      'pão doce',
      'muffin',
      'cupcake',
      'torrada',
      'bagel',
      'donut',
      'churro',
      'mil folhas',
      'croissant de chocolate',
      'croissant de queijo',
      'quiche',
      'empada',
      'esfirra',
      'pastel',
      'pao frances',
      'pão francês',
      'pao de leite',
      'pão de leite',
      'pao de alho',
      'pão de alho',
      'pizza',
      'fatia de bolo',
      'pave',
      'pavê',
      'trufa',
      'eclair',
      'profiterole',
      'choux',
      'merengue',
      'suspiro',
      'torrone',
      'tarte',
      'creme brulee',
      'crème brûlée',
      'baba de camelo',
      'rabanada',
      'brioche',
      'baguete integral',
      'pao australiano',
      'pão australiano',
      'bolo de rolo',
      'bolo de laranja',
      'bolo de chocolate',
      'bolo de fubá',
      'bolo de milho',
      'bolo de cenoura',
      'suflê',
      'cannoli',
      'biscotti',
      'cantuccini',
      'beignet',
      'pandoro',
      'panetone',
      'colomba pascal',
      'babka',
      'strudel',
      'cronut'
    ];

    List<String> laticinios = [
      'leite',
      'queijo',
      'manteiga',
      'iogurte',
      'creme de leite',
      'coalhada',
      'leite condensado',
      'leite em po',
      'leite em pó',
      'creme de leite fresco',
      'requeijao',
      'requeijão',
      'queijo minas',
      'queijo coalho',
      'queijo prato',
      'queijo ricota',
      'queijo gorgonzola',
      'queijo parmesao',
      'queijo parmesão',
      'queijo cottage',
      'queijo roquefort',
      'queijo brie',
      'queijo camembert',
      'leite desnatado',
      'leite integral',
      'leite semidesnatado',
      'leite de cabra',
      'leite de soja',
      'leite de amêndoas',
      'leite de coco',
      'leite de arroz',
      'leite de aveia',
      'leite de castanha',
      'leite de avelã',
      'nata',
      'creme de leite sem lactose',
      'leite fermentado',
      'leite fermentado probiotico',
      'leite fermentado probiótico',
      'queijo mussarela',
      'queijo provolone',
      'queijo cheddar',
      'queijo estepe',
      'queijo gruyere',
      'queijo gruyère',
      'queijo edam',
      'queijo emmental',
      'queijo de cabra',
      'queijo de ovelha',
      'queijo tipo suíço',
      'queijo tipo suico',
      'queijo tipo reino',
      'queijo cottage desnatado',
      'ricota fresca',
      'queijo feta',
      'queijo mascarpone',
      'queijo azul',
      'queijo tipo boursin',
      'creme de queijo',
      'manteiga sem sal',
      'manteiga com sal',
      'margarina',
      'margarina light',
      'creme vegetal',
      'chantilly',
      'nata fresca',
      'nata batida',
      'leite condensado diet',
      'leite condensado sem lactose',
      'leite condensado de soja',
      'leite evaporado',
      'leite condensado de coco',
      'leite de kefir',
      'leite de kefir desnatado',
      'leite de kefir integral',
      'iogurte natural',
      'iogurte natural desnatado',
      'iogurte natural integral',
      'iogurte de frutas',
      'iogurte com mel',
      'iogurte com cereais',
      'coalhada seca',
      'cream cheese',
      'creme fraiche',
      'crème fraîche',
      'queijo de cabra fresco',
      'queijo de cabra curado',
      'queijo cottage com ervas',
      'queijo cottage com frutas'
    ];

    List<String> frios = [
      'presunto',
      'mortadela',
      'salame',
      'patê',
      'peito de peru',
      'blanquet de peru',
      'salaminho',
      'linguiça calabresa',
      'presunto parma',
      'salchicha',
      'salsicha',
      'linguiça toscana',
      'linguiça portuguesa',
      'frango defumado',
      'lombo canadense',
      'presunto cozido',
      'presunto cru',
      'pastrami',
      'roast beef',
      'bacon',
      'bacon em tiras',
      'bacon em cubos',
      'presunto de frango',
      'presunto de porco',
      'queijo de Minas',
      'queijo prato',
      'queijo mussarela',
      'queijo parmesão',
      'queijo ricota',
      'queijo gorgonzola',
      'queijo feta',
      'queijo gruyère',
      'queijo camembert',
      'queijo brie',
      'queijo roquefort',
      'queijo cheddar',
      'queijo de cabra',
      'queijo cottage',
      'cream cheese',
      'queijo provolone',
      'salsichão',
      'salame italiano',
      'mortadela italiana',
      'mortadela com pistache',
      'presunto defumado',
      'presunto de Parma',
      'presunto de peito de frango',
      'presunto de peito de peru'
    ];

    List<String> limpeza = [
      'água desmineralizada',
      'agua desmineralizada',
      'água sanitária',
      'agua sanitária',
      'álcool',
      'alcool',
      'álcool em gel',
      'alcool em gel',
      'amaciador de roupas',
      'amaciante',
      'anti-mofos',
      'anti mofos',
      'anti-manchas',
      'anti manchas',
      'aparelho de limpeza a vapor',
      'borrifador',
      'borrifador de água',
      'borrifador de agua',
      'cera automotiva',
      'cera de carnaúba',
      'cera de carnauba',
      'cera líquida',
      'cera liquida',
      'cera para piso',
      'cera polidora',
      'cleaner',
      'cloro',
      'cloro gel',
      'creme de limpeza',
      'creme de polimento',
      'desengordurante',
      'desengordurante de cozinha',
      'desengordurante para forno',
      'desengordurante potente',
      'desinfetante',
      'desinfetante concentrado',
      'desinfetante de banheiro',
      'desinfetante de cozinha',
      'desinfetante hospitalar',
      'desinfetante para piso',
      'desinfetante suave',
      'detergente',
      'detergente líquido',
      'detergente liquido',
      'detergente neutro',
      'detergente para máquina',
      'detergente para maquina',
      'esponja',
      'esponja de aço',
      'esponja de limpeza',
      'esponja mágica',
      'esponja magica',
      'flanela',
      'gel desengordurante',
      'guardanapo de papel',
      'limpa alumínio',
      'limpa aluminio',
      'limpa fornos',
      'limpa inox',
      'limpa janelas',
      'limpa móveis',
      'limpa moveis',
      'limpa telhas',
      'limpa vidros',
      'limpador de banheiro',
      'limpador de carpetes',
      'limpador de cozinha',
      'limpador de estofados',
      'limpador de janelas',
      'limpador de superfícies',
      'limpador de superficies',
      'limpador de vidros',
      'limpador multiuso',
      'limpador perfumado',
      'lustra móveis',
      'lustra moveis',
      'microfibra de limpeza',
      'neutralizador de odores',
      'odorizador de ambientes',
      'pano de chão',
      'pano de chao',
      'pano de microfibra',
      'pano multiuso',
      'papel higiênico',
      'papel higienico',
      'polidor de metais',
      'polidor de móveis',
      'polidor de moveis',
      'produto anti-bacteriano',
      'produto anti-séptico',
      'produto anti-septico',
      'produto de limpeza ecológico',
      'produto de limpeza ecologico',
      'produto de limpeza multiuso',
      'produto de limpeza pesada',
      'produto de limpeza rápida',
      'produto de limpeza rapida',
      'produto de polimento',
      'removedor de manchas',
      'removedor de mofo',
      'removedor de tintas',
      'repelente de insetos',
      'sabão de coco',
      'sabao de coco',
      'sabão em pó',
      'sabao em po',
      'sabão líquido',
      'sabao liquido',
      'spray de limpeza',
      'squeegee',
      'squeeze de limpeza',
      'tira manchas',
      'vassoura',
      'vassoura de cerdas',
      'vassoura elétrica',
      'vassoura eletrica',
      'vassoura mágica',
      'vassoura magica'
    ];

    List<String> higienePessoal = [
      'absorvente',
      'água micelar', 'agua micelar', // Com e sem acento
      'algodão', 'algodao', // Com e sem acento
      'antisséptico bucal', 'antisseptico bucal', // Com e sem acento
      'balm para barba',
      'bastão anti-transpirante',
      'bastao anti-transpirante', // Com e sem acento
      'bastão para calos', 'bastao para calos', // Com e sem acento
      'cera depilatória', 'cera depilatoria', // Com e sem acento
      'colônia', 'colonia', // Com e sem acento
      'condicionador',
      'condicionador infantil',
      'condicionador sem sulfato',
      'cotonete',
      'creme anti-idade',
      'creme de barbear',
      'creme de depilação', 'creme de depilacao', // Com e sem acento
      'creme de mãos', 'creme de maos', // Com e sem acento
      'creme depilatório', 'creme depilatorio', // Com e sem acento
      'creme esfoliante',
      'creme hidratante',
      'creme para as mãos', 'creme para as maos', // Com e sem acento
      'creme para cabelo cacheado',
      'creme para celulite',
      'creme para estrias',
      'creme para olheiras',
      'creme para pés', 'creme para pes', // Com e sem acento
      'creme para pentear',
      'creme para rachaduras',
      'creme revitalizante',
      'creme suavizante',
      'creme dental',
      'creme para lábios', 'creme para labios', // Com e sem acento
      'creme para olhos',
      'curativos adesivos',
      'descolorante',
      'desodorante',
      'desodorante aerossol',
      'desodorante em bastão', 'desodorante em bastao', // Com e sem acento
      'desodorante em creme',
      'desodorante em gel',
      'desodorante em spray',
      'desodorante roll-on',
      'desodorante sem perfume',
      'escova de cabelo',
      'escova dental',
      'esfoliante corporal',
      'esfoliante facial',
      'esmalte de unhas',
      'espuma de barbear',
      'fio dental',
      'fralda descartável', 'fralda descartavel', // Com e sem acento
      'gel antibacteriano',
      'gel de banho',
      'gel fixador',
      'gel íntimo', 'gel intimo', // Com e sem acento
      'gel para cabelo',
      'gel pós-barba', 'gel pos-barba', // Com e sem acento
      'hidratante corporal',
      'hidratante facial',
      'hidratante para as mãos', 'hidratante para as maos', // Com e sem acento
      'hidratante para o corpo',
      'hidratante para o rosto',
      'kit de depilação', 'kit de depilacao', // Com e sem acento
      'lenços umedecidos', 'lencos umedecidos', // Com e sem acento
      'limpa pele',
      'loção corporal', 'locao corporal', // Com e sem acento
      'loção pós-barba', 'locao pos-barba', // Com e sem acento
      'loção para o corpo', 'locao para o corpo', // Com e sem acento
      'loção para o rosto', 'locao para o rosto', // Com e sem acento
      'máscara capilar', 'mascara capilar', // Com e sem acento
      'máscara facial', 'mascara facial', // Com e sem acento
      'manteiga corporal',
      'óleo corporal', 'oleo corporal', // Com e sem acento
      'óleo facial', 'oleo facial', // Com e sem acento
      'óleo para cabelo', 'oleo para cabelo', // Com e sem acento
      'pente de cabelo',
      'perfume',
      'pó compacto', 'po compacto', // Com e sem acento
      'pomada capilar',
      'pomada modeladora',
      'protetor de calcinha',
      'protetor labial',
      'protetor solar',
      'protetor solar corporal',
      'protetor solar facial',
      'repelente de insetos',
      'sabonete',
      'sabonete antibacteriano',
      'sabonete em barra',
      'sabonete líquido', 'sabonete liquido', // Com e sem acento
      'shampoo', 'xampu', // Com e sem acento
      'shampoo anticaspa',
      'shampoo infantil',
      'talco para pés', 'talco para pes', // Com e sem acento
      'tônico capilar', 'tonico capilar', // Com e sem acento
      'tônico facial', 'tonico facial' // Com e sem acento
    ];

    List<String> bebidas = [
      'água', 'agua', // Com e sem acento
      'água com gás', 'agua com gás', // Com e sem acento
      'água de coco', 'agua de coco', // Com e sem acento
      'aguardente',
      'aperitivo',
      'batida',
      'batida de coco',
      'bebida energética',
      'bebida isotônica', 'bebida isotonica', // Com e sem acento
      'bloody mary',
      'brandy',
      'caipirinha',
      'caipiroska',
      'café', 'cafe', // Com e sem acento
      'café gelado', 'cafe gelado', // Com e sem acento
      'café latte', 'cafe latte', // Com e sem acento
      'café mocha', 'cafe mocha', // Com e sem acento
      'cappuccino',
      'cava', // Espumante espanhol
      'cachaça',
      'chá', 'cha', // Com e sem acento
      'chá de camomila', 'cha de camomila', // Com e sem acento
      'chá de erva-doce', 'cha de erva-doce', // Com e sem acento
      'chá de hibisco', 'cha de hibisco', // Com e sem acento
      'chá gelado', 'cha gelado', // Com e sem acento
      'chá mate', 'cha mate', // Com e sem acento
      'champanhe', 'champagne', // Alternativas para espumante
      'cidra',
      'cider', // Alternativa para sidra
      'clericot',
      'coca-cola',
      'conhaque',
      'cosmopolitan',
      'creme de whisky',
      'curaçao blue', 'curacao blue', // Com e sem acento
      'dry martini',
      'energético', 'energetico', // Com e sem acento
      'espumante',
      'frappuccino',
      'frozen',
      'gin',
      'gin tônica', 'gin tonica', // Com e sem acento
      'groselha',
      'iced tea',
      'ice',
      'irish coffee',
      'licor',
      'licor de frutas',
      'licor de menta',
      'licor de chocolate',
      'limonada',
      'long island iced tea',
      'mate',
      'mojito',
      'margarita',
      'moscow mule',
      'negroni',
      'piña colada', 'pina colada', // Com e sem acento
      'ponche',
      'refrigerante',
      'refresco',
      'rum',
      'sangria',
      'saquê', 'sake', // Com e sem acento
      'sidra',
      'smoothie',
      'spritz',
      'suco',
      'suco de abacaxi',
      'suco de acerola',
      'suco de amora',
      'suco de caju',
      'suco de cranberry',
      'suco de goiaba',
      'suco de laranja',
      'suco de limão', 'suco de limao', // Com e sem acento
      'suco de maçã', 'suco de maca', // Com e sem acento
      'suco de maracujá', 'suco de maracuja', // Com e sem acento
      'suco de melancia',
      'suco de melão', 'suco de melao', // Com e sem acento
      'suco de morango',
      'suco de pêssego', 'suco de pessego', // Com e sem acento
      'suco de tamarindo',
      'suco de tomate',
      'suco de uva',
      'tequila',
      'tonica',
      'vermouth',
      'vermute',
      'vinho',
      'vinho branco',
      'vinho espumante',
      'vinho rosé', 'vinho rose', // Com e sem acento
      'vinho tinto',
      'vodca', 'vodka', // Com e sem acento
      'whisky'
    ];

    List<String> mercearia = [
      'açúcar', 'acucar', // Com e sem acento
      'açúcar cristal', 'acucar cristal', // Com e sem acento
      'açúcar de coco', 'acucar de coco', // Com e sem acento
      'açúcar de confeiteiro', 'acucar de confeiteiro', // Com e sem acento
      'açúcar mascavo', 'acucar mascavo', // Com e sem acento
      'açúcar orgânico', 'acucar organico', // Com e sem acento
      'amido de milho',
      'arroz',
      'arroz arbóreo',
      'arroz integral',
      'arroz parboilizado',
      'aveia em flocos',
      'aveia instantânea',
      'bacon',
      'bacon em cubos',
      'bacon em tiras',
      'barras de cereal',
      'biscoito',
      'biscoito amanteigado',
      'biscoito de arroz',
      'biscoito doce',
      'biscoito de doce',
      'biscoito de maizena', 'biscoito de maisena',// Com e sem acento
      'biscoito maizena',
      'biscoito de polvilho',
      'biscoito de queijo',
      'biscoito de sal',
      'biscoito doce',
      'biscoito integral',
      'biscoito para pet',
      'biscoito salgado',
      'bolo de aniversário',
      'bolo de chocolate',
      'bolo de cenoura',
      'bolo de frutas',
      'bolo de fubá',
      'bolo de milho',
      'bolo de laranja',
      'bolo de maçã', 'bolo de maca', // Com e sem acento
      'bolo de rolo',
      'caldo de carne',
      'caldo de galinha',
      'caldo de legumes',
      'caldo de peixe',
      'café', 'cafe', // Com e sem acento
      'café em grão',
      'café solúvel',
      'cereal',
      'cereal matinal',
      'chocolate',
      'chocolate amargo',
      'chocolate ao leite',
      'chocolate branco',
      'chocolate em pó',
      'chocolate meio amargo',
      'chocolate preto',
      'cogumelos',
      'condimentos',
      'conserva de legumes',
      'creme de arroz',
      'creme de leite condensado',
      'creme de leite fresco',
      'creme de leite light',
      'farinha',
      'farinha de aveia',
      'farinha de coco',
      'farinha de centeio',
      'farinha de espelta',
      'farinha de milho',
      'farinha de rosca',
      'farinha de trigo',
      'farinha de trigo integral',
      'farinha de grão-de-bico', 'farinha de grao-de-bico', // Com e sem acento
      'farinha de mandioca',
      'farinha de arroz',
      'farinha de batata',
      'farinha de quinoa',
      'feijão', 'feijao', // Com e sem acento
      'feijão azuki', 'feijao azuki', // Com e sem acento
      'feijão bolinha', 'feijao bolinha', // Com e sem acento
      'feijão branco', 'feijao branco', // Com e sem acento
      'feijão carioca', 'feijao carioca', // Com e sem acento
      'feijão de corda',
      'feijão de rosa',
      'feijão fradinho', 'feijao fradinho', // Com e sem acento
      'feijão jalo', 'feijao jalo', // Com e sem acento
      'feijão macassa',
      'feijão moído', 'feijao moido', // Com e sem acento
      'feijão mulatinho', 'feijao mulatinho', // Com e sem acento
      'feijão preto', 'feijao preto', // Com e sem acento
      'feijão rajado', 'feijao rajado', // Com e sem acento
      'feijão roxo', 'feijao roxo', // Com e sem acento
      'feijão verde', 'feijao verde', // Com e sem acento
      'flocos de arroz',
      'flocos de milho',
      'gelatina',
      'geleia',
      'geleia de frutas',
      'geleia de morango',
      'geleia de pêssego', 'geleia de pessego', // Com e sem acento
      'geleia de uva',
      'granola',
      'macarrão', 'macarrao', // Com e sem acento
      'maionese',
      'margarina',
      'margarina culinária',
      'mel',
      'melado de cana',
      'manteiga',
      'mel de abelha',
      'mel de flores',
      'mel de laranjeira',
      'mel de eucalipto',
      'molho barbecue',
      'molho inglês',
      'molho de soja',
      'molho shoyu',
      'óleo', 'oleo', // Com e sem acento
      'pasta de dente', 'pasta de dentes', // Adicional
      'pipoca',
      'polvilho azedo',
      'polvilho doce',
      'presunto em conserva',
      'sequilhos',
      'vinagre',
      'vinagre balsâmico', 'vinagre balsamico', // Com e sem acento
      'vinagre de maçã', 'vinagre de maca', // Com e sem acento
      'vinagre de arroz',
      'vinagre de vinho',
      'xarope de agave',
      'xarope de bordo',
      'arroz arbóreo',
      'arroz selvagem',
      'azúcar de confeiteiro', // Variedade em espanhol
      'biscoito de polvilho',
      'biscoito de queijo',
      'bolo de maracujá',
      'bolo de milho com goiabada',
      'bolo de maçã', 'bolo de maca', // Com e sem acento
      'caldo de legumes',
      'caldo de peixe',
      'cereal matinal',
      'chocolate em pó',
      'chocolate meio amargo',
      'chocolate preto',
      'cogumelo seco',
      'creme de leite em pó',
      'farinha de arroz',
      'farinha de batata',
      'farinha de grão-de-bico',
      'farinha de quinoa',
      'feijão carioca em grão',
      'feijão preto em grão',
      'gelatina em pó',
      'geleia de damasco',
      'geleia de kiwi',
      'geleia de morango sem açúcar',
      'manteiga de amendoim',
      'mel de eucalipto',
      'molho barbecue',
      'molho inglês',
      'óleo de coco',
      'óleo de girassol',
      'pasta de amendoim',
      'pasta de tomate',
      'polvilho doce',
      'polvilho para bolos',
      'vinagre de maçã orgânico',
      'vinagre de maca organico', // Com e sem acento
      'xarope de agave orgânico'
    ];

    // Verificar o produto
    if (carnes.contains(nomeProduto.toLowerCase())) {
      return Categoria.carnes.nomeFormatado;
    } else if (hortifruti.contains(nomeProduto.toLowerCase())) {
      return Categoria.hortifruti.nomeFormatado;
    } else if (padaria.contains(nomeProduto.toLowerCase())) {
      return Categoria.padaria.nomeFormatado;
    } else if (laticinios.contains(nomeProduto.toLowerCase())) {
      return Categoria.laticinios.nomeFormatado;
    } else if (frios.contains(nomeProduto.toLowerCase())) {
      return Categoria.frios.nomeFormatado;
    } else if (limpeza.contains(nomeProduto.toLowerCase())) {
      return Categoria.limpeza.nomeFormatado;
    } else if (higienePessoal.contains(nomeProduto.toLowerCase())) {
      return Categoria.higienePessoal.nomeFormatado;
    } else if (bebidas.contains(nomeProduto.toLowerCase())) {
      return Categoria.bebidas.nomeFormatado;
    } else if (mercearia.contains(nomeProduto.toLowerCase())) {
      return Categoria.mercearia.nomeFormatado;
    } else {
      return Categoria.indefinido.nomeFormatado;
    }
  }
}

/* 
      default:
        return obterCategoriaAleatoria().nomeFormatado;
*/